environment:
  JAVA_6_HOME: C:\Program Files\Java\jdk1.6.0\
  JAVA_7_HOME: C:\Program Files\Java\jdk1.7.0\
  JAVA_8_HOME: C:\Program Files\Java\jdk1.8.0\
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0\


install:
  -  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e

test_script:
  - mvn clover2:setup test -Ptest clover2:aggregate clover2:clover  -Dmaven.test.failure.ignore=true -e

build: off